version: '3'
services: 
  db:
    image: mongo
    volumes:
      - mongo-db:/data/db
      - mongo-dump:/dump
    command: mongod --smallfiles

  rocketchat:
    image: rocketchat/rocket.chat:latest
    environment:
      - MONGO_URL=mongodb://db:27017/rocketchat
      - ROOT_URL=http://localhost
      - Accounts_UseDNSDomainCheck=True
    ports:
      - 3000:3000

volumes:
  mongo-db:
  mongo-dump:
